version: '3.7'
services:
  web:
    build: .
    image: bi-bilby:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=db:27017
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on: 
      - db
  db:
    image: mongo:4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
